import SvgIcon from '../../shared-components/SvgIcon.js';

function normalizeTextblockTokens(col) {
  const container = col;
  if (!container) return;

  const paragraphs = Array.from(
    container.querySelectorAll(':scope p')
  );

  const textblockClasses = [];

  paragraphs.reverse().forEach((p) => {
    const token = p.textContent.trim();

    if (!token.startsWith('textblock-')) return;

    const classes = token.split(/\s+/);
    if (classes.every((c) => c.startsWith('textblock-'))) {
      textblockClasses.push(...classes);
      p.remove();
    }
  });

  // Clean up empty <p> tags left behind (e.g. wrapper generated by Editor)
  container.querySelectorAll(':scope p').forEach((p) => {
    if (p.textContent.trim() === '' && p.children.length === 0) {
      p.remove();
    }
  });

  // Only apply textblock styles if there is still actual content left
  if (textblockClasses.length > 0) {
    if (container.textContent.trim() !== '' || container.querySelector('picture, img, .block, svg, h1, h2, h3, h4, h5, h6')) {
      container.classList.add('textblock', ...textblockClasses);
    }
  }
}

function renderBrandedIcon(block) {
  if (block.querySelector(':scope > .columns-branded-icon')) return;

  const iconWrapper = document.createElement('div');
  iconWrapper.className = 'columns-branded-icon';
  iconWrapper.innerHTML = SvgIcon({ name: 'brandRings' });

  block.prepend(iconWrapper);
}

export default function decorate(block) {
  block.classList.add('columns-block', 'fade-item');
  block.classList.add('container');
  const rows = Array.from(block.children)
    .filter((el) => !el.classList.contains('columns-branded-icon'));

  block.classList.add(`columns-${rows.length}-cols`);
  block.classList.add(`columns-cols`);

  rows.forEach((row) => {
    row.classList.add('columns-row');

    Array.from(row.children).forEach((col) => {
      col.classList.add('columns-col');

      const pic = col.querySelector(':scope > picture');
      if (
        pic &&
        col.children.length === 1 &&
        !col.querySelector('.block')
      ) {
        col.classList.add('columns-img-col');
      }

      normalizeTextblockTokens(col);

      // Remove the column entirely if it has no content after normalization
      if (col.textContent.trim() === '' && col.children.length === 0) {
        col.remove();
      }
    });

    // Remove the row entirely if all its columns were empty and removed
    if (row.children.length === 0) {
      row.remove();
    }
  });

  if (block.classList.contains('has-icon')) {
    renderBrandedIcon(block);
  }
}
